version: '3.8'

services:
  backend:
    build: ./backend
    container_name: sales-backend
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/sales_dashboard
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: sales-frontend
    ports:
      - "80:80"

  mongo:
    image: mongo
    container_name: sales-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
